spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    # connection_url/db_name
    url: jdbc:postgresql://localhost:5432/batch14_user_management
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl: none
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis: # redis as database
      host: localhost
      port: 6379
      client-type: lettuce # jenis client yg populer, ada 1 lagi "jedis"
      timeout: 10s
      connect-timeout: 10s
      database: 0  # jenis database (0-16)
    cache: # sbenarnya tidak hanya redis
      type: redis  #makanya di sini type=redis, buat pake redis
      redis:
        use-key-prefix: true
        key-prefix: "cache:user-service:"
        cache-null-values: true
        time-to-live: 600s

server:
  port: 8081
  servlet:
    context-path: /user-service

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: Trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret-key: JSKSIIERUJSJSLDI0208U383976767OI
  expired-in: 3

management:
  health:
    redis:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health